name: Pull Request Merge Comment

on:
  pull_request_target:
    types:
      - "closed"
    branches:
      - "master"

permissions:
  issues: write
  pull-requests: write

jobs:
  comment_on_merge:
    if: github.repository == 'codinasion/first-pull-request' && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'harshraj8843'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `Thanks very much for contributing!

              Your pull request has been merged 🎉

              Support this project by giving it a star ⭐. 

              If you're looking for your next contribution, please check out [our other open source projects](https://github.com/orgs/codinasion/repositories).`
            })
